name:    espial
synopsis: Espial is an open-source, web-based bookmarking server.
version: "0.0.11"
description: ! '

  Espial is an open-source, web-based bookmarking server.

  - Yesod + PureScript + sqlite3

  - multi-user (w/ privacy scopes)
  
  - tags, stars, editing, deleting
'
category: Web
author: Jon Schoning
maintainer: jonschoning@gmail.com
copyright: Copyright (c) 2018 Jon Schoning
license: AGPL-3
license-file: LICENSE
homepage: https://github.com/jonschoning/espial
git: git://github.com/jonschoning/espial.git
bug-reports: https://github.com/jonschoning/espial/issues
extra-source-files:
- README.md
- changelog.md
- config/favicon.ico
- config/keter.yml
- config/robots.txt
- config/routes
- config/settings.yml
- config/test-settings.yml
- templates/**
- static/css/**
- static/images/**
- static/js/**
- purs/Makefile
- purs/packages.dhall
- purs/spago.dhall
- purs/src/**
- purs/src/**/Component/**
- purs/test/**

default-extensions:
- BangPatterns
- BlockArguments
- CPP
- ConstraintKinds
- DataKinds
- DeriveDataTypeable
- DeriveGeneric
- DerivingStrategies      
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- PolyKinds
- PolymorphicComponents
- PartialTypeSignatures
- QuasiQuotes
- Rank2Types
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
- ViewPatterns

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

- yesod >=1.6 && <1.8
- yesod-core >=1.6 && <1.8
- yesod-auth >=1.6 && <1.8
- yesod-static >=1.6 && <1.8
- yesod-form >=1.6 && <1.8
- yesod-newsfeed >= 1.6 && < 1.8
- classy-prelude >=1.4 && <1.6
- classy-prelude-conduit >=1.4 && <1.6
- classy-prelude-yesod >=1.4 && <1.6
- bytestring >=0.9 && <0.11
- text >=0.11 && <2.0
- persistent >=2.8 && <2.14
- blaze-html >= 0.9 && < 1.0
- persistent-template >=2.5 && <2.13
- template-haskell
- shakespeare >=2.0 && <2.1
- hjsmin >=0.1 && <0.3
- wai-extra >=3.0 && <3.2
- yaml >=0.8 && <0.12
- http-client-tls >=0.3 && <0.4
- http-conduit >=2.3 && <2.4
- directory >=1.1 && <1.4
- warp >=3.0 && <3.4
- data-default
- conduit >=1.0 && <2.0
- monad-logger >=0.3 && <0.4
- fast-logger >=2.2 && <4
- wai-logger
- file-embed
- safe
- unordered-containers
- containers
- vector
- time
- case-insensitive
- wai
- foreign-store

- aeson >=1.4
- attoparsec
- bcrypt >= 0.0.8
- entropy
- esqueleto
- hscolour
- http-api-data >= 0.3.4
- http-client
- http-types
- iso8601-time >=0.1.3
- microlens
- mtl
- persistent-sqlite >=2.6.2
- pretty-show
- transformers >= 0.2.2
- parser-combinators
- html-entities
- connection
- base64
- cryptohash-sha256

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  espial:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - espial
    when:
    - condition: flag(library-only)
      buildable: false
  migration:
    when:
      - condition: flag(library-only)
        buildable: false
    main: Main.hs
    source-dirs:
      - app/migration
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - espial
      - optparse-generic >= 1.2.3
      - optparse-applicative

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - espial
    - hspec >=2.0.0
    - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
