name:    espial
synopsis: Espial is an open-source, web-based bookmarking server.
version: "0.0.1"
description: ! '

  Espial is an open-source, web-based bookmarking server.

  - Yesod + sqlite3

  - multi-user (w/ privacy scopes)
  
  - tags, stars, editing, deleting
'
category: Web
author: Jon Schoning
maintainer: jonschoning@gmail.com
copyright: Copyright (c) 2018 Jon Schoning
license: MIT
homepage: https://github.com/jonschoning/espial
git: git://github.com/jonschoning/espial.git
bug-reports: https://github.com/jonschoning/espial/issues
extra-source-files:
- README.md
- changelog.md

default-extensions:
- BangPatterns
- CPP
- ConstraintKinds
- DeriveDataTypeable
- DeriveGeneric
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeOperators
- ViewPatterns

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

# version 1.0 had a bug in reexporting Handler, causing trouble
- classy-prelude-yesod >=0.10.2 && <1.0 || >=1.1

- aeson >=0.6 && <1.3
- bytestring >=0.9 && <0.11
- case-insensitive
- classy-prelude >=0.10.2
- classy-prelude-conduit >=0.10.2
- conduit >=1.0 && <2.0
- containers
- data-default
- directory >=1.1 && <1.4
- esqueleto
- fast-logger >=2.2 && <2.5
- file-embed
- foreign-store
- hjsmin >=0.1 && <0.3
- http-conduit >=2.1 && <2.3
- monad-control >=0.3 && <1.1
- monad-logger >=0.3 && <0.4
- mtl
- transformers >= 0.2.2
- persistent >=2.0 && <2.8
- persistent-sqlite >=2.6.2 && <2.8
- persistent-template >=2.0 && <2.8
- safe
- shakespeare >=2.0 && <2.1
- template-haskell
- text >=0.11 && <2.0
- time
- unordered-containers
- vector
- wai
- wai-extra >=3.0 && <3.1
- wai-logger >=2.2 && <2.4
- warp >=3.0 && <3.3
- yaml >=0.8 && <0.9
- yesod >=1.4.3 && <1.5
- yesod-auth >=1.4.0 && <1.5
- yesod-core >=1.4.30 && <1.5
- yesod-form >=1.4.0 && <1.5
- yesod-static >=1.4.0.3 && <1.6
- hscolour
- pretty-show
- bcrypt >= 0.0.8 && <0.0.11
- iso8601-time >=0.1.3 && <0.2.0


# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  espial:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - espial
    when:
    - condition: flag(library-only)
      buildable: false
  migration:
    when:
      - condition: flag(library-only)
        buildable: false
    main: Main.hs
    source-dirs:
      - app/migration
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - espial
      - optparse-generic >= 1.2.3

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - espial
    - hspec >=2.0.0
    - yesod-test
    - microlens

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
