-- if the 'usebuildinfo' flag is set, this module should be generated by the build system and contain the git sha of the current commit
module BuildInfo where

import Prelude (String)

gitSha :: String
gitSha = "UNKNOWN"