on: [push]
name: CI
jobs:
  stack:
    name: Stack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      with:
        enable-stack: true
        stack-version: "latest"

    - uses: actions/cache@v3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-lts-24.37

    - name: Build
      run: |
        stack build --stack-yaml stack.yaml --test --bench --no-run-tests --no-run-benchmarks --fast

    - name: Test
      run: |
        stack test --stack-yaml stack.yaml --fast
